export const INIT_CATEGORIES = [
  { id: 1, label: 'Food', type: 'expense', icon: '🍴' },
  { id: 2, label: 'Fun', type: 'expense', icon: '😊' },
  { id: 3, label: 'Supplies', type: 'expense', icon: '🛒' },
  { id: 4, label: 'Insurance', type: 'expense', icon: '📃' },
  { id: 5, label: 'Pharma', type: 'expense', icon: '💊' },
  { id: 6, label: 'Transport', type: 'expense', icon: '🚌' },
  { id: 7, label: 'Utilities', type: 'expense', icon: '⚡' },
  { id: 8, label: 'Misc.', type: 'expense', icon: '💬' },
  { id: 9, label: 'Salary', type: 'income', icon: '💰' },
  { id: 10, label: 'Wage', type: 'income', icon: '💰' },
  { id: 11, label: 'Investment', type: 'income', icon: '💲' },
  { id: 12, label: 'Gift', type: 'income', icon: '🎁' },
  { id: 13, label: 'Misc.', type: 'income', icon: '💬' },
];

export const DUMMY_QUERIES = [
  {
    id: 'Food',
    title: 'Food',
    date: '2022-10-24',
    sum: 57,
    trend: -22,
  },
  {
    id: 'Utilities',
    title: 'Utilities',
    date: '2022-10-22',
    sum: 234.03,
    trend: -6,
  },
  {
    id: 'Fun',
    title: 'Fun',
    date: '2022-10-20',
    sum: 248,
    trend: 14,
  },
  {
    id: 'Work',
    title: 'Work',
    date: '2022-10-19',
    sum: 324,
    trend: -7,
  },
  {
    id: 'Transport',
    title: 'Transport',
    date: '2022-10-15',
    sum: 32,
    trend: -6,
  },
  {
    id: 'Pharma',
    title: 'Pharma',
    date: '2022-10-14',
    sum: 104,
    trend: 11,
  },
];
